In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
import numpy as np
import pandas as pd

In [4]:
array = np.random.random((2, 6))
array = np.empty((9, 9))
array = np.arange(1, 10, 2)
array = np.arange(81).reshape((9, 9))
array = np.linspace(10, 99, 20).reshape((5, 4))

array

array([[10.        , 14.68421053, 19.36842105, 24.05263158],
       [28.73684211, 33.42105263, 38.10526316, 42.78947368],
       [47.47368421, 52.15789474, 56.84210526, 61.52631579],
       [66.21052632, 70.89473684, 75.57894737, 80.26315789],
       [84.94736842, 89.63157895, 94.31578947, 99.        ]])

In [45]:
# np.sum(array)
# np.min(array)
# np.max(array)
# np.sum(array, axis=0)
# np.min(array, axis=0)
# np.max(array, axis=1)
# np.argmin(array)
# np.argmax(array)
# np.median(array)
# np.cumsum(array)
# np.diff(array)
# np.nonzero(array)
# np.sort(array)
# np.transpose(array)
# np.clip(array, 30, 70)

In [46]:
# array[0][3]
# array[4, :]
# array[:, 3]
# array[0, 2:4]

# for row in array:
#     print(row)

# for col in array.T:
#     print(col)

# for item in array.flat:
#     print(item)

In [55]:
np.split(array, 5, axis=0)
np.split(array, 2, axis=1)

np.array_split(array, 5, axis=1)

np.vsplit(array, 5)
# np.hsplit(array, 4)

# A1 = array
# A2 = array.copy()

# A1[0] = 100
# A2[1] = 200


[array([[10.        , 14.68421053, 19.36842105, 24.05263158]]),
 array([[28.73684211, 33.42105263, 38.10526316, 42.78947368]]),
 array([[47.47368421, 52.15789474, 56.84210526, 61.52631579]]),
 array([[66.21052632, 70.89473684, 75.57894737, 80.26315789]]),
 array([[84.94736842, 89.63157895, 94.31578947, 99.        ]])]

In [58]:
A = np.arange(0, 10)
B = np.arange(-9, 1)

C = np.vstack((A, B))
C.shape
C

D = np.hstack((A, B))
# D.shape
D

A[np.newaxis, :]
A[:, np.newaxis]

# E = np.concatenate((A, B), axis=0)

# E

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [63]:
import random

arr = [random.random() * 100 for i in range(10)]
nparr = np.array(arr)
nparr = np.round(nparr, 2)

nparr

array([57.  , 72.34, 18.95, 98.52,  6.78, 28.98, 17.4 , 48.27,  3.65,
       26.31])

In [5]:
float_formatter = lambda x: "%.4f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})

In [9]:
stocks = pd.read_csv('./FTSE_CHINA_A50_INDEX.csv', dtype={'symbol': str})
# stocks.symbol.astype(str)

narr = np.random.uniform(-50, 100, size=(50, 2)) / 100
narr = np.round(narr, 4)

In [10]:
data_list = [
    ['MSFT', 'Microsoft Corp', 135.4202, -0.235794, 0.029663, 'Information Technology'],
    ['AAPL', 'Apple Inc.', 242.2136, -0.182374, 0.044825, 'Information Technology'],
    ['AMZN', 'Amazon.com Inc', 1689.1552, -0.126587, 0.092764, 'Consumer Discretionary'],
    ['FB', 'Facebook Inc A', 146.0148, -0.377137,  0.031919, 'Communication Services'],
    ['GOOG', 'Alphabet Inc A', 1084.3379, -0.274243, 0.048383, 'Communication Services'],
]

df = pd.DataFrame(data_list, columns=['Symbol', 'Company', 'Price', '1Wk Return', '1Mon Return', 'Sector'])
# df[['Price', '1Wk Return', '1Mon Return']] = df[['Price', '1Wk Return', '1Mon Return']].astype(float)
df['Price'] = df['Price'].round(decimals=2)
df['1Wk Return'] = df['1Wk Return'].apply(lambda x: '%.2f' % (x * 100) + '%')
df['1Mon Return'] = df['1Mon Return'].apply(lambda x: '{0:.2f}%'.format (x * 100))
df = pd.concat([df] * 10)
df = df.sample(frac=1).reset_index(drop=True)

In [11]:
t = np.arange(24).reshape(4,6)
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
np.where(t < 10, 0, np.where(t > 20, 20, t))

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20]])

In [13]:
t.clip(10, 20)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20]])

In [14]:
np.eye(6)

array([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
       [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
       [0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
       [0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000],
       [0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000],
       [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000]])

In [17]:
np.random.rand(3, 4)
np.random.randn(3, 4)
np.random.randint(1, 12, (3, 4))
np.random.uniform(1, 12, (3, 4))
np.random.normal(1, 12, (3, 4))

array([[0.7583, 0.8822, 0.1834, 0.9409],
       [0.4668, 0.2773, 0.1999, 0.4890],
       [0.7058, 0.1908, 0.4258, 0.5113]])

array([[-0.9600, -2.3256, -0.8559, 2.9237],
       [-0.1951, -0.0524, 1.4366, -0.4864],
       [0.0027, 0.0196, -1.3084, -1.8952]])

array([[ 2,  1,  3,  5],
       [ 3, 11,  3, 11],
       [ 5,  3, 10,  9]])

array([[7.6670, 5.2327, 8.2011, 3.8400],
       [6.9729, 9.2396, 6.8205, 2.8742],
       [11.2337, 9.8622, 3.5659, 9.6736]])

array([[8.9861, -21.9537, 4.3910, 5.5887],
       [-12.5938, 1.1384, -2.2640, 1.9940],
       [-19.0286, 7.0247, -0.4820, 20.0994]])

In [18]:
year = 2016
event = 'Referendum'
p = f'Results of the {year} {event}'
p

'Results of the 2016 Referendum'

In [6]:
score = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

In [8]:
type(score)

numpy.ndarray

In [47]:
import pdfkit